version: '3'
services:
  db:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    

  web:
    build: .

    env_file:
      - ./.env

    volumes:
      - .:/backend-app

    ports:
      - "5000:5000"
      
    depends_on:
      - db


