version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=giganotosecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=giganoto
    ports:
      - 5432:5432
    

  web:
    build: .

    environment:
      - DATABASE_URI=postgresql://postgres:giganotosecret@db:5432/giganoto
      - PYTHONUNBUFFERED=1
      - CLOUDFLARE_ACCOUNT_ID=cloudflareid
      - AWS_ACCESS_KEY_ID=aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=aws_secret_access_key

    volumes:
      - .:/backend-app

    ports:
      - "5000:5000"
      
    depends_on:
      - db


